# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Desktop\Qvost.sk\Universal\Universal\quart-ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Currency(object):
    def setupUi(self, Currency):
        Currency.setObjectName("Currency")
        Currency.resize(1367, 840)
        Currency.setAutoFillBackground(False)
        Currency.setStyleSheet("font-family: Verdana;\n"
"background: #f0f0f0;\n"
"text-transform: uppercase;")
        self.centralwidget = QtWidgets.QWidget(Currency)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.Console = QtWidgets.QTextEdit(self.centralwidget)
        self.Console.setGeometry(QtCore.QRect(940, 650, 371, 161))
        self.Console.setAutoFillBackground(False)
        self.Console.setStyleSheet("background: white;\n"
"border: 1px solid black;")
        self.Console.setReadOnly(True)
        self.Console.setObjectName("Console")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(-10, 0, 1381, 91))
        self.widget_3.setStyleSheet("background-color: #21325E;")
        self.widget_3.setObjectName("widget_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 20))
        self.label.setStyleSheet("color: white;\n"
"border: none;\n"
"font-family: Verdana;\n"
"font-size: 24px;\n"
"font-weight: bold;\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 161, 20))
        self.label_2.setStyleSheet("color: white;\n"
"border: none;\n"
"font-family: Verdana;\n"
"font-size: 14px;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(70, 50, 1251, 41))
        self.widget_4.setStyleSheet("background: white;\n"
"border: 1px solid gray;")
        self.widget_4.setObjectName("widget_4")
        self.COM_slot = QtWidgets.QComboBox(self.widget_4)
        self.COM_slot.setGeometry(QtCore.QRect(30, 10, 61, 21))
        self.COM_slot.setStyleSheet("border: none;\n"
"background: white;\n"
"")
        self.COM_slot.setFrame(False)
        self.COM_slot.setObjectName("COM_slot")
        self.BR_slot = QtWidgets.QComboBox(self.widget_4)
        self.BR_slot.setGeometry(QtCore.QRect(100, 10, 61, 21))
        self.BR_slot.setStyleSheet("border-radius: 5px; \n"
"border: none;\n"
"")
        self.BR_slot.setFrame(False)
        self.BR_slot.setObjectName("BR_slot")
        self.connButton = QtWidgets.QPushButton(self.widget_4)
        self.connButton.setGeometry(QtCore.QRect(170, 10, 71, 23))
        self.connButton.setStyleSheet("border: none;\n"
"padding: 0px;\n"
"margin: 0px;\n"
"")
        self.connButton.setObjectName("connButton")
        self.discButton = QtWidgets.QPushButton(self.widget_4)
        self.discButton.setGeometry(QtCore.QRect(250, 10, 81, 23))
        self.discButton.setStyleSheet("border: none;\n"
"padding: 0px;\n"
"margin: 0px;")
        self.discButton.setObjectName("discButton")
        self.opengl = QtWidgets.QFrame(self.centralwidget)
        self.opengl.setGeometry(QtCore.QRect(60, 139, 840, 671))
        self.opengl.setStyleSheet("")
        self.opengl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.opengl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.opengl.setObjectName("opengl")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(940, 620, 371, 31))
        self.label_3.setStyleSheet("font-family: Verdana;\n"
"color: white;\n"
"background: #3E497A;\n"
"padding: 6px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 110, 841, 31))
        self.label_4.setStyleSheet("font-family: Verdana;\n"
"color: white;\n"
"background: #3E497A;\n"
"padding: 6px;")
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(940, 350, 371, 251))
        self.widget.setStyleSheet("background: white;\n"
"border: 1px solid black;")
        self.widget.setObjectName("widget")
        self.X_slider = QtWidgets.QSlider(self.widget)
        self.X_slider.setGeometry(QtCore.QRect(10, 20, 301, 22))
        self.X_slider.setStyleSheet("border: none;")
        self.X_slider.setMinimum(-180)
        self.X_slider.setMaximum(180)
        self.X_slider.setOrientation(QtCore.Qt.Horizontal)
        self.X_slider.setObjectName("X_slider")
        self.Y_slider = QtWidgets.QSlider(self.widget)
        self.Y_slider.setGeometry(QtCore.QRect(10, 50, 301, 22))
        self.Y_slider.setStyleSheet("border: none;")
        self.Y_slider.setMinimum(-120)
        self.Y_slider.setMaximum(120)
        self.Y_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Y_slider.setObjectName("Y_slider")
        self.Z_slider = QtWidgets.QSlider(self.widget)
        self.Z_slider.setGeometry(QtCore.QRect(10, 80, 301, 21))
        self.Z_slider.setStyleSheet("border: none;")
        self.Z_slider.setMinimum(-160)
        self.Z_slider.setMaximum(160)
        self.Z_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Z_slider.setObjectName("Z_slider")
        self.startButton = QtWidgets.QPushButton(self.widget)
        self.startButton.setGeometry(QtCore.QRect(100, 180, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("border: 1px solid black;\n"
"background: #F0f0f0;\n"
"")
        self.startButton.setObjectName("startButton")
        self.homingButton = QtWidgets.QPushButton(self.widget)
        self.homingButton.setGeometry(QtCore.QRect(10, 150, 81, 23))
        self.homingButton.setStyleSheet("border: 1px solid black;\n"
"background: #F0f0f0;\n"
"font-weight: bold;\n"
"")
        self.homingButton.setObjectName("homingButton")
        self.loadButton = QtWidgets.QPushButton(self.widget)
        self.loadButton.setGeometry(QtCore.QRect(10, 180, 81, 23))
        self.loadButton.setStyleSheet("border: 1px solid black;\n"
"background: #F0f0f0;\n"
"font-weight: bold;\n"
"")
        self.loadButton.setObjectName("loadButton")
        self.moveButton = QtWidgets.QPushButton(self.widget)
        self.moveButton.setGeometry(QtCore.QRect(10, 210, 81, 23))
        self.moveButton.setStyleSheet("border: 1px solid black;\n"
"background: #F0f0f0;\n"
"font-weight: bold;\n"
"")
        self.moveButton.setObjectName("moveButton")
        self.A_slider = QtWidgets.QSlider(self.widget)
        self.A_slider.setGeometry(QtCore.QRect(10, 110, 301, 22))
        self.A_slider.setStyleSheet("border: none;")
        self.A_slider.setMaximum(360)
        self.A_slider.setOrientation(QtCore.Qt.Horizontal)
        self.A_slider.setObjectName("A_slider")
        self.X_lcd = QtWidgets.QLabel(self.widget)
        self.X_lcd.setGeometry(QtCore.QRect(330, 20, 31, 16))
        self.X_lcd.setStyleSheet("font-size: 16px;")
        self.X_lcd.setObjectName("X_lcd")
        self.Y_lcd = QtWidgets.QLabel(self.widget)
        self.Y_lcd.setGeometry(QtCore.QRect(330, 50, 31, 16))
        self.Y_lcd.setStyleSheet("font-size: 16px;")
        self.Y_lcd.setObjectName("Y_lcd")
        self.Z_lcd = QtWidgets.QLabel(self.widget)
        self.Z_lcd.setGeometry(QtCore.QRect(330, 80, 31, 16))
        self.Z_lcd.setStyleSheet("font-size: 16px;")
        self.Z_lcd.setObjectName("Z_lcd")
        self.A_lcd = QtWidgets.QLabel(self.widget)
        self.A_lcd.setGeometry(QtCore.QRect(330, 110, 31, 16))
        self.A_lcd.setStyleSheet("font-size: 16px;")
        self.A_lcd.setObjectName("A_lcd")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(10, 120, 351, 20))
        self.line.setStyleSheet("border-left: none;\n"
"border-right: none;\n"
"border-top: none;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.create_MacroButton = QtWidgets.QPushButton(self.widget)
        self.create_MacroButton.setGeometry(QtCore.QRect(100, 150, 261, 23))
        self.create_MacroButton.setStyleSheet("border: 1px solid black;\n"
"background: #F0f0f0;\n"
"font-weight: bold;\n"
"")
        self.create_MacroButton.setObjectName("create_MacroButton")
        self.save_PosButton = QtWidgets.QPushButton(self.widget)
        self.save_PosButton.setGeometry(QtCore.QRect(240, 180, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.save_PosButton.setFont(font)
        self.save_PosButton.setStyleSheet("border: 1px solid black;\n"
"background: #F0f0f0;\n"
"")
        self.save_PosButton.setObjectName("save_PosButton")
        self.save_MacroButton = QtWidgets.QPushButton(self.widget)
        self.save_MacroButton.setGeometry(QtCore.QRect(240, 210, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.save_MacroButton.setFont(font)
        self.save_MacroButton.setStyleSheet("border: 1px solid black;\n"
"background: #F0f0f0;\n"
"")
        self.save_MacroButton.setObjectName("save_MacroButton")
        self.line.raise_()
        self.X_slider.raise_()
        self.Y_slider.raise_()
        self.Z_slider.raise_()
        self.startButton.raise_()
        self.homingButton.raise_()
        self.loadButton.raise_()
        self.moveButton.raise_()
        self.A_slider.raise_()
        self.X_lcd.raise_()
        self.Y_lcd.raise_()
        self.Z_lcd.raise_()
        self.A_lcd.raise_()
        self.create_MacroButton.raise_()
        self.save_PosButton.raise_()
        self.save_MacroButton.raise_()
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(940, 320, 371, 31))
        self.label_5.setStyleSheet("font-family: Verdana;\n"
"color: white;\n"
"background: #3E497A;\n"
"padding: 6px;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(940, 110, 371, 31))
        self.label_6.setStyleSheet("font-family: Verdana;\n"
"color: white;\n"
"background: #3E497A;\n"
"padding: 6px;")
        self.label_6.setObjectName("label_6")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(940, 140, 371, 161))
        self.widget_2.setStyleSheet("background: white;\n"
"border: 1px solid black;")
        self.widget_2.setObjectName("widget_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.widget_5.setStyleSheet("background: #F0F0F0;\n"
"border: 1px solid black;")
        self.widget_5.setObjectName("widget_5")
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setGeometry(QtCore.QRect(15, 5, 31, 31))
        self.label_7.setStyleSheet("font-size: 32px;\n"
"border: none;\n"
"")
        self.label_7.setObjectName("label_7")
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setGeometry(QtCore.QRect(70, 10, 291, 41))
        self.widget_6.setStyleSheet("background: #F0F0F0;\n"
"border: 1px solid black;")
        self.widget_6.setObjectName("widget_6")
        self.label_12 = QtWidgets.QLabel(self.widget_6)
        self.label_12.setGeometry(QtCore.QRect(5, 5, 281, 31))
        self.label_12.setStyleSheet("font-size: 32px;\n"
"border: none;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.widget_8 = QtWidgets.QWidget(self.widget_2)
        self.widget_8.setGeometry(QtCore.QRect(70, 60, 291, 41))
        self.widget_8.setStyleSheet("background: #F0F0F0;\n"
"border: 1px solid black;")
        self.widget_8.setObjectName("widget_8")
        self.label_13 = QtWidgets.QLabel(self.widget_8)
        self.label_13.setGeometry(QtCore.QRect(5, 5, 281, 31))
        self.label_13.setStyleSheet("font-size: 32px;\n"
"border: none;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.widget_9 = QtWidgets.QWidget(self.widget_2)
        self.widget_9.setGeometry(QtCore.QRect(70, 110, 291, 41))
        self.widget_9.setStyleSheet("background: #F0F0F0;\n"
"border: 1px solid black;")
        self.widget_9.setObjectName("widget_9")
        self.label_14 = QtWidgets.QLabel(self.widget_9)
        self.label_14.setGeometry(QtCore.QRect(5, 5, 281, 31))
        self.label_14.setStyleSheet("font-size: 32px;\n"
"border: none;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setGeometry(QtCore.QRect(10, 60, 51, 41))
        self.widget_7.setStyleSheet("background: #F0F0F0;\n"
"border: 1px solid black;")
        self.widget_7.setObjectName("widget_7")
        self.label_10 = QtWidgets.QLabel(self.widget_7)
        self.label_10.setGeometry(QtCore.QRect(15, 5, 31, 31))
        self.label_10.setStyleSheet("font-size: 32px;\n"
"border: none;\n"
"")
        self.label_10.setObjectName("label_10")
        self.widget_10 = QtWidgets.QWidget(self.widget_2)
        self.widget_10.setGeometry(QtCore.QRect(10, 110, 51, 41))
        self.widget_10.setStyleSheet("background: #F0F0F0;\n"
"border: 1px solid black;")
        self.widget_10.setObjectName("widget_10")
        self.label_11 = QtWidgets.QLabel(self.widget_10)
        self.label_11.setGeometry(QtCore.QRect(15, 5, 31, 31))
        self.label_11.setStyleSheet("font-size: 32px;\n"
"border: none;\n"
"")
        self.label_11.setObjectName("label_11")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(940, 790, 371, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.widget_2.raise_()
        self.Console.raise_()
        self.widget_3.raise_()
        self.opengl.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.widget.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.lineEdit.raise_()
        Currency.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Currency)
        self.statusbar.setObjectName("statusbar")
        Currency.setStatusBar(self.statusbar)

        self.retranslateUi(Currency)
        QtCore.QMetaObject.connectSlotsByName(Currency)

    def retranslateUi(self, Currency):
        _translate = QtCore.QCoreApplication.translate
        Currency.setWindowTitle(_translate("Currency", "Universal"))
        self.label.setText(_translate("Currency", "Universal"))
        self.label_2.setText(_translate("Currency", "Q-Code Controller"))
        self.connButton.setText(_translate("Currency", "Connect"))
        self.discButton.setText(_translate("Currency", "Disconnect"))
        self.label_3.setText(_translate("Currency", "Console"))
        self.label_4.setText(_translate("Currency", "Viewport"))
        self.startButton.setText(_translate("Currency", "LOAD"))
        self.homingButton.setText(_translate("Currency", "Homing"))
        self.loadButton.setText(_translate("Currency", "MOVE TO"))
        self.moveButton.setText(_translate("Currency", "Move"))
        self.X_lcd.setText(_translate("Currency", "0"))
        self.Y_lcd.setText(_translate("Currency", "0"))
        self.Z_lcd.setText(_translate("Currency", "0"))
        self.A_lcd.setText(_translate("Currency", "0"))
        self.create_MacroButton.setText(_translate("Currency", "CREATE MACRO"))
        self.save_PosButton.setText(_translate("Currency", "SAVE POS"))
        self.save_MacroButton.setText(_translate("Currency", "SAVE MACRO"))
        self.label_5.setText(_translate("Currency", "Control"))
        self.label_6.setText(_translate("Currency", "CURRENT POSITION"))
        self.label_7.setText(_translate("Currency", "X"))
        self.label_12.setText(_translate("Currency", "0.0000"))
        self.label_13.setText(_translate("Currency", "0.0000"))
        self.label_14.setText(_translate("Currency", "0.0000"))
        self.label_10.setText(_translate("Currency", "Y"))
        self.label_11.setText(_translate("Currency", "Z"))
